name: php-laravel
recipe: laravel
config:
  webroot: public
  php: "8.2"
  via: nginx
services:
  appserver:
    build:
      - php artisan key:generate
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  pma:
    - "pma.php-laravel.lndo.site"
